/**
 * GenUI scorecard harness. Scores a corpus of openui-lang exemplar screens on
 * three axes:
 *  (a) contract validity - every component exists in the library and its
 *      (recursively unwrapped) props pass the component's zod schema, plus
 *      the openui-lang parser reports no validation errors;
 *  (b) headless render success through both design-system libraries
 *      (filled in by the jest-expo rig in __tests__/scorecard.test.tsx);
 *  (c) the unknown-component list - names the model used that render as
 *      NOTHING in this app (react-lang returns null for unknown components).
 * See docs/scorecard.md for the methodology.
 */
import { createParser } from "@openuidev/react-lang";
import type { ElementNode, Library } from "@openuidev/react-lang";

export interface ScreenScore {
  name: string;
  contractOk: boolean;
  /** zod/parser prop validation failures, "Component.path: message". */
  propErrors: string[];
  unknownComponents: string[];
  /** Sorted names of every component the screen uses. */
  components: string[];
  /** null until the render rig fills them in. */
  cupertinoOk: boolean | null;
  materialOk: boolean | null;
  renderNotes: string[];
}

function isElement(value: unknown): value is ElementNode {
  return (
    !!value && typeof value === "object" && (value as { type?: unknown }).type === "element"
  );
}

/**
 * The parser wraps sub-components as ElementNodes ({type, typeName, props,
 * partial}), while a component's zod schema (via `.ref`) expects the plain
 * props object. Unwrap recursively so safeParse checks the real shape.
 */
function unwrap(value: unknown): unknown {
  if (isElement(value)) return unwrapProps(value.props);
  if (Array.isArray(value)) return value.map(unwrap);
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value as Record<string, unknown>).map(([k, v]) => [k, unwrap(v)]),
    );
  }
  return value;
}

function unwrapProps(props: Record<string, unknown>): Record<string, unknown> {
  return Object.fromEntries(Object.entries(props).map(([k, v]) => [k, unwrap(v)]));
}

/** Depth-first collection of every element in a parsed tree. */
export function collectElements(root: ElementNode | null): ElementNode[] {
  const out: ElementNode[] = [];
  const walk = (value: unknown) => {
    if (isElement(value)) {
      out.push(value);
      Object.values(value.props).forEach(walk);
    } else if (Array.isArray(value)) {
      value.forEach(walk);
    } else if (value && typeof value === "object") {
      Object.values(value).forEach(walk);
    }
  };
  walk(root);
  return out;
}

/** Score (a) contract validity and (c) unknown components for one screen. */
export function scoreContract(name: string, source: string, library: Library): ScreenScore {
  const score: ScreenScore = {
    name,
    contractOk: false,
    propErrors: [],
    unknownComponents: [],
    components: [],
    cupertinoOk: null,
    materialOk: null,
    renderNotes: [],
  };

  let result;
  try {
    result = createParser(library.toJSONSchema()).parse(source);
  } catch (err) {
    score.propErrors.push(`parse failed: ${err instanceof Error ? err.message : String(err)}`);
    return score;
  }

  const unknown = new Set<string>();
  for (const err of result.meta.errors) {
    if (err.code === "unknown-component") unknown.add(err.component);
    else score.propErrors.push(`${err.component}${err.path}: ${err.message}`);
  }

  const elements = collectElements(result.root);
  score.components = [...new Set(elements.map((el) => el.typeName))].sort();
  for (const el of elements) {
    const def = library.components[el.typeName];
    if (!def) {
      unknown.add(el.typeName);
      continue;
    }
    const check = def.props.safeParse(unwrapProps(el.props));
    if (!check.success) {
      for (const issue of check.error.issues.slice(0, 3)) {
        score.propErrors.push(`${el.typeName}.${issue.path.join(".")}: ${issue.message}`);
      }
    }
  }

  if (result.meta.incomplete) score.propErrors.push("program parses as incomplete/truncated");
  if (!result.root) score.propErrors.push("no root element parsed");

  score.unknownComponents = [...unknown].sort();
  score.contractOk =
    result.root !== null &&
    !result.meta.incomplete &&
    score.unknownComponents.length === 0 &&
    score.propErrors.length === 0;
  return score;
}

function mark(value: boolean | null): string {
  if (value === null) return "-";
  return value ? "pass" : "FAIL";
}

/** Render the full scorecard as a markdown table (written to SCORECARD.md). */
export function formatScorecard(scores: ScreenScore[], contractComponents: string[]): string {
  const lines: string[] = [
    "# GenUI Scorecard",
    "",
    "Generated by `npm run scorecard` - do not edit by hand. See docs/scorecard.md.",
    "",
    "| screen | contract | cupertino | material | unknown components |",
    "| --- | --- | --- | --- | --- |",
  ];
  for (const s of scores) {
    lines.push(
      `| ${s.name} | ${mark(s.contractOk)} | ${mark(s.cupertinoOk)} | ${mark(s.materialOk)} | ${s.unknownComponents.join(", ") || "-"} |`,
    );
  }

  const failing = scores.filter((s) => !s.contractOk || s.cupertinoOk === false || s.materialOk === false);
  lines.push("", `**${scores.length - failing.length}/${scores.length} screens pass all three checks.**`, "");
  for (const s of failing) {
    lines.push(`### ${s.name}`);
    for (const e of s.propErrors) lines.push(`- ${e}`);
    for (const n of s.renderNotes) lines.push(`- ${n}`);
    lines.push("");
  }

  const used = new Set(scores.flatMap((s) => s.components));
  const missing = contractComponents.filter((c) => !used.has(c)).sort();
  lines.push(
    `## Component coverage: ${used.size}/${contractComponents.length}`,
    "",
    missing.length > 0 ? `Not covered: ${missing.join(", ")}` : "Every contract component is covered.",
    "",
  );
  return lines.join("\n");
}
