/**
 * Embed the generated openui-lang system prompt as a TS module (Metro has no
 * raw-text imports). The prompt is produced by the appless-os web repo's
 * `openui generate` step; this script adapts it to the native contract and
 * embeds it. Regenerate with `npm run generate:prompt <path-to-prompt.txt>`
 * whenever the component contract changes.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const src = process.argv[2] ?? join(root, "../appless-os/src/generated/system-prompt.txt");
const out = join(root, "src/genos/generated/system-prompt.ts");

if (!existsSync(src)) {
  console.error(
    `embed-prompt: prompt source not found: ${src}\n\n` +
      "Pass the path to a generated openui system prompt explicitly:\n" +
      "  npm run generate:prompt -- /path/to/system-prompt.txt\n\n" +
      "(The default path assumes the appless-os web repo is checked out as a\n" +
      "sibling directory and its prompt has been generated with `pnpm dev`.)",
  );
  process.exit(1);
}

let prompt = readFileSync(src, "utf-8").trimEnd();

// Adapt the web prompt to the native contract: components the native
// renderer sets don't implement must not be offered to the model - unknown
// components render as NOTHING (react-lang returns null), so a form field
// the model emits would silently vanish.
prompt = prompt.replace(/ \| CheckBoxGroup \| RadioGroup/g, "");

// Normalize em/en dashes to hyphens.
prompt = prompt.replace(/[\u2014\u2013]/g, "-");

mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  `// AUTO-GENERATED by scripts/embed-prompt.mjs - do not edit by hand.\n` +
    `// Regenerate with: npm run generate:prompt\n` +
    `export const SYSTEM_PROMPT = ${JSON.stringify(prompt)};\n`,
);
console.log(`embedded ${prompt.length} chars → ${out}`);
