/**
 * Bake the OpenUI Cloud request config into a TS module (Metro has no raw-text
 * imports, and @openuidev/thesys-server is Node-only so it cannot ship in the
 * app bundle).
 *
 * generateSystemPrompt() emits the `]]>openui:config` block that tells OpenUI
 * Cloud which component library to generate against and which AppLess prompt
 * options to fold into its server-side system prompt. Everything it needs -
 * the schema and the prose - lives in src, so regenerate with
 * `npm run generate:prompt` whenever the contract or the prompt spec changes.
 */
import { generateSystemPrompt } from "@openuidev/thesys-server";
import * as esbuild from "esbuild";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "src/genos/generated/system-prompt.ts");

// The contract is TSX and pulls in zod + react-lang; bundle it for Node and
// import it from memory. Renderers only decide how components look, so a stub
// per component is enough to build the library and its schema.
const bundle = await esbuild.build({
  stdin: {
    contents: `
      import { buildGenosLibrary } from "./src/genos/ui/contract";
      import { buildChatLibrary } from "./src/genos/chatLibrary";
      import { ADDITIONAL_RULES, EXAMPLES, PREAMBLE } from "./src/genos/promptSpec";
      const stubRenderers = new Proxy({}, { get: () => () => null });
      export const chatLibrary = buildChatLibrary(buildGenosLibrary(stubRenderers));
      export const promptOptions = {
        preamble: PREAMBLE,
        additionalRules: ADDITIONAL_RULES,
        examples: EXAMPLES,
      };
    `,
    resolveDir: root,
    loader: "ts",
  },
  bundle: true,
  platform: "node",
  format: "esm",
  write: false,
});

const { chatLibrary, promptOptions } = await import(
  `data:text/javascript;base64,${Buffer.from(bundle.outputFiles[0].text).toString("base64")}`
);

const prompt = generateSystemPrompt({ library: chatLibrary, promptOptions });

mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  `// AUTO-GENERATED by scripts/generate-prompt.mjs - do not edit by hand.\n` +
    `// Regenerate with: npm run generate:prompt\n` +
    `export const SYSTEM_PROMPT = ${JSON.stringify(prompt)};\n`,
);
console.log(
  `embedded ${prompt.length} chars (${Object.keys(chatLibrary.schema.$defs ?? {}).length} components) → ${out}`,
);
